### PR TITLE
Adds the ability to provide a function for notNull

### PR DESCRIPTION
**Pull request by variousauthors**
- in some cases the user would like to return more
   than just a string

### CODE REVIEW

**Comment by alexdrel** [comment]
Hi,
Thank you for the pull request, I will merge it right now but I have a few questions and one request.

- Do you think that with a function NotFound can be considered a fallback mechanism as well and as such should be processed with format as a normal result?
- Are you OK with me making a small cosmetic change or two?
-  Can I burden you with updating README as well to make this feature discoverable?

Thanks again,
Alex

**Comment by variousauthors** [comment]
Oh hmm! I don't use the markdown feature so I hadn't even thought of that. If it was processed with format, then the user could provide a notFound like,

```
(key: string) => `${key} was _missing_`
```

and then it would be rendered something like, "key was _missing_"?

Sure!

Please feel free to make any kinds of changes you like. I've tried to mimic your coding style as much as possible, but you know best.

I will update the readme!

**Comment by variousauthors** [comment]
Hey hey, I have discovered a weirdness! My current implementation of `notFound` is like this:

```tsx
    notFound: (key: string) => {
      // if the key _is_ in the master list, then
      // just return `T.key` so that 
      // we know translation is missing for that key
      if (locales[LocaleType.EN][key]) {
        return `T.${key}`
      } else {
        // if the key is missing from the master list
        // then return `{{KEY}}` to draw attention
        // to the missing key
        return `{{${key.toLocaleUpperCase()}}}`
      }
    }
```

This actually causes an infinite loop, because {{KEY_NAME}} recursively tries to replace itself with itself? I think it is because the returned string is being interpolated by MD.

This may be intended behaviour, but it should be documented as a gotcha, or maybe you can detect an infinite regress (checking for `prev_key === next_key` type thing...?).

**Comment by variousauthors** [comment]
Hmm also, after changing the second case to return strings like `M.SOME_KEY` I noticed that I sometimes ended up seeing `T.M.SOME_KEY` in the output... so there may be some issues here...

**Comment by alexdrel** [comment]
Hi, with ``{{}}`` you literally hit self-referencing feature, which allows referencing another translation key from the dictionary.  Like this
```
- hello: 'Hello'
- hi: {{hello}} // Hello
```
I wonder if it is documented at all :) But it is definitely used and useful.

You can use double backtick syntax to screen ``{{}}``.
```
  "``{{" + key.toLocaleUpperCase() + "}}``"
```

**Pull request merged**
