### PR TITLE
enhance the literal syntax to allow nesting of backticks

### PR DESCRIPTION
**Pull request by steven-qi**
With current literal syntax, there is no way to render ``` `` ``` as-is.

This PR implemented a solution that allows nesting of backtick pairs unlimited, just like what GitHub did.

Examples:
 -  ```` ``` `` ``` ```` => ``` `` ```
 -  ```` `` ``` `` ```` => `` ``` ``
 - ````` ```` ``` `` ``` ```` ````` => ```` ``` `` ``` ````

Note:
 - any leading/trailing spaces will be trimmed in the literal expression. Just move spaces outside of literal expression should be fine.
 - a function instead of regex is used to parse literal, as it is not possible to be achieved with regex especially when `look-behind` is not yet widely supported.

### CODE REVIEW

**Comment by steven-qi** [comment]
Hi @alexdrel let me know what do you think about this.

**Comment by steven-qi** [comment]
@alexdrel I have no idea why CI is failing.

**Comment by alexdrel** [comment]
Hi @steven-qi,
First Travis error has nothing to do with you PR. They changed the way firefox should be started, I am fixing it now in 6c796c9.
I am not ready yet to abandon regexes and write parses by hand, it looks like with some changes and `look-ahead` it's possible to catch matching numbers of back-ticks and a whitespace. 
[/^(.*?(?:(?!`).|^))(``+)\s(.*?)\s\2(?!`)(.*)$/](https://regex101.com/r/1M9umF/1).
I will use your unit tests to check it.

**Comment by alexdrel** [comment]
@steven-qi please take a look at dc2194cb4b4943eb22677b7268757dda6d74bf5f , it passes all the tests but may be you have other use cases for literals.

**Comment by steven-qi** [comment]
Yes, I do have more test cases: 
1. all leading/tailing spaces between open/close token should be removed, instead of only first/last spaces (to be fully compatible with GitHub).
2. `` ```abc``` `` should render `abc` (ie, spaces should be optional unless the content is start/end with `` ` ``)
3. `` ```abc```` `` should not be considered as valid literals.

**Comment by steven-qi** [comment]
Especially for the latest one, I have no idea how to implement it without `look-behind`, that's the reason I changed to a parser function.

**Comment by alexdrel** [comment]
> all leading/tailing spaces between open/close token should be removed, instead of only first/last spaces (to be fully compatible with GitHub).

Not exactly, I just checked it in this preview - GitHub strips only one space ``` ``  b  `` ``` gets transformed to ``<code>  b </code>``. Extra spaces are not shown by ``<code>`` tag itself. See for yourself: ``             ``.

**Comment by alexdrel** [comment]
@steven-qi I updated legacy (no space) regex to also use matching number logic.
It passes your new tests as well. I'm slightly worried about breaking compatibility but it hardly justifies release MDFlavor v2. See 16e8aa4317ed02e880aea3b8828c828fe7ffb02e.

**Comment by steven-qi** [comment]
@alexdrel great 👍 

yes, it will be a breaking change for v1 literal... but if first/last spaces are not ignored, there is no way for user to render ``` `` ```.

**Comment by steven-qi** [comment]
@alexdrel I'm closing this PR, as your implementation looks promise and satisfied all my requirements 👍

**Comment by alexdrel** [comment]
Published ``` ``0.7.0`` ``` :)

**Pull request closed without merging**
